# Generated by Django 5.0.3 on 2024-03-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snob', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'course category', 'verbose_name_plural': 'course categories'},
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_price', models.FloatField()),
                ('course_duration', models.CharField(max_length=30)),
                ('course_description', models.TextField()),
                ('course_image', models.FileField(upload_to='snob_images')),
                ('course_teacher', models.CharField(max_length=50)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snob.categorymodel')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
