# Generated by Django 5.0.3 on 2024-03-20 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snob', '0002_alter_categorymodel_options_coursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='course_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
