# Generated by Django 5.0.3 on 2024-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snob', '0003_coursemodel_course_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_description',
            field=models.TextField(help_text='добавьте описание к вашему курсу'),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_duration',
            field=models.CharField(help_text='добавьте продолжительность вашего курса', max_length=30),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_teacher',
            field=models.CharField(help_text='фамилия и имя преподавателя данного курса', max_length=50),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='course_title',
            field=models.CharField(help_text='добавьте название вашего курса', max_length=50),
        ),
    ]
