# Generated by Django 5.0.3 on 2024-03-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snob', '0004_alter_coursemodel_course_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_icon',
            field=models.FileField(default=None, upload_to='snob_images'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(help_text='добавьте название вашего курса', max_length=50)),
                ('book_pages', models.IntegerField(help_text='добавьте количество страниц в книге')),
                ('book_description', models.TextField(help_text='добавьте описание к вашему курсу')),
                ('book_image', models.FileField(upload_to='snob_images')),
                ('book_author', models.CharField(help_text='фамилия и имя автора', max_length=50)),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snob.categorymodel')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(help_text='добавьте имя и фамилию преподавателя', max_length=50)),
                ('teacher_experience', models.IntegerField(help_text='какой опыт работы учителя?')),
                ('teacher_profession', models.TextField(help_text='что преподает этот учитель?')),
                ('teacher_image', models.FileField(upload_to='snob_images')),
                ('teacher_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snob.categorymodel')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
    ]
